name: Bug report
description: Report incorrect or unexpected behavior of a package.
labels: [bug, 'bug:unverified']
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: textarea
    id: codesample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: TypeScript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which version of are you using? Run `npm list <package>` in your project directory and paste the output.
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
  - type: input
    id: next-release
    attributes:
      label: I have tested this issue on a next release
      placeholder: d309e0a (commit hash)
      description: |
        The issue might already be fixed in a next release or main. This is not required, but helps us greatly.
        To install the latest next development release run `npm i package@next` in your project directory.
        Run `npm list package` and use the 2nd last part of the printed information (`d309e0a` for `package@x.x.x-next.d309e0a.0`)
